//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("Faqdeu", "PerfilUsuario", "Perfil", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(TestEntityFramework.Perfil), "Usuario", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(TestEntityFramework.Usuario))]
[assembly: EdmRelationshipAttribute("Faqdeu", "CarreraCarrerasxEntidad", "Carrera", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(TestEntityFramework.Carrera), "CarrerasxEntidad", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(TestEntityFramework.CarrerasxEntidad), true)]
[assembly: EdmRelationshipAttribute("Faqdeu", "EntidadCarrerasxEntidad", "Entidad", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(TestEntityFramework.Entidad), "CarrerasxEntidad", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(TestEntityFramework.CarrerasxEntidad), true)]
[assembly: EdmRelationshipAttribute("Faqdeu", "CarrerasxEntidadProfesoresxCarreraxEntidad", "CarrerasxEntidad", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(TestEntityFramework.CarrerasxEntidad), "ProfesoresxCarreraxEntidad", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(TestEntityFramework.ProfesoresxCarreraxEntidad), true)]
[assembly: EdmRelationshipAttribute("Faqdeu", "ProfesorProfesoresxCarreraxEntidad", "Profesor", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(TestEntityFramework.Profesor), "ProfesoresxCarreraxEntidad", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(TestEntityFramework.ProfesoresxCarreraxEntidad), true)]

#endregion

namespace TestEntityFramework
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class FaqdeuContainer : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new FaqdeuContainer object using the connection string found in the 'FaqdeuContainer' section of the application configuration file.
        /// </summary>
        public FaqdeuContainer() : base("name=FaqdeuContainer", "FaqdeuContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new FaqdeuContainer object.
        /// </summary>
        public FaqdeuContainer(string connectionString) : base(connectionString, "FaqdeuContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new FaqdeuContainer object.
        /// </summary>
        public FaqdeuContainer(EntityConnection connection) : base(connection, "FaqdeuContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Perfil> Perfiles
        {
            get
            {
                if ((_Perfiles == null))
                {
                    _Perfiles = base.CreateObjectSet<Perfil>("Perfiles");
                }
                return _Perfiles;
            }
        }
        private ObjectSet<Perfil> _Perfiles;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Usuario> Usuarios
        {
            get
            {
                if ((_Usuarios == null))
                {
                    _Usuarios = base.CreateObjectSet<Usuario>("Usuarios");
                }
                return _Usuarios;
            }
        }
        private ObjectSet<Usuario> _Usuarios;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Entidad> Entidades
        {
            get
            {
                if ((_Entidades == null))
                {
                    _Entidades = base.CreateObjectSet<Entidad>("Entidades");
                }
                return _Entidades;
            }
        }
        private ObjectSet<Entidad> _Entidades;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Profesor> Profesores
        {
            get
            {
                if ((_Profesores == null))
                {
                    _Profesores = base.CreateObjectSet<Profesor>("Profesores");
                }
                return _Profesores;
            }
        }
        private ObjectSet<Profesor> _Profesores;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Carrera> Carreras
        {
            get
            {
                if ((_Carreras == null))
                {
                    _Carreras = base.CreateObjectSet<Carrera>("Carreras");
                }
                return _Carreras;
            }
        }
        private ObjectSet<Carrera> _Carreras;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<CarrerasxEntidad> CarrerasxEntidades
        {
            get
            {
                if ((_CarrerasxEntidades == null))
                {
                    _CarrerasxEntidades = base.CreateObjectSet<CarrerasxEntidad>("CarrerasxEntidades");
                }
                return _CarrerasxEntidades;
            }
        }
        private ObjectSet<CarrerasxEntidad> _CarrerasxEntidades;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ProfesoresxCarreraxEntidad> ProfesoresxCarreraesxEntidades
        {
            get
            {
                if ((_ProfesoresxCarreraesxEntidades == null))
                {
                    _ProfesoresxCarreraesxEntidades = base.CreateObjectSet<ProfesoresxCarreraxEntidad>("ProfesoresxCarreraesxEntidades");
                }
                return _ProfesoresxCarreraesxEntidades;
            }
        }
        private ObjectSet<ProfesoresxCarreraxEntidad> _ProfesoresxCarreraesxEntidades;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Formulario> Formularios
        {
            get
            {
                if ((_Formularios == null))
                {
                    _Formularios = base.CreateObjectSet<Formulario>("Formularios");
                }
                return _Formularios;
            }
        }
        private ObjectSet<Formulario> _Formularios;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Perfiles EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToPerfiles(Perfil perfil)
        {
            base.AddObject("Perfiles", perfil);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Usuarios EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToUsuarios(Usuario usuario)
        {
            base.AddObject("Usuarios", usuario);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Entidades EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToEntidades(Entidad entidad)
        {
            base.AddObject("Entidades", entidad);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Profesores EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToProfesores(Profesor profesor)
        {
            base.AddObject("Profesores", profesor);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Carreras EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCarreras(Carrera carrera)
        {
            base.AddObject("Carreras", carrera);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the CarrerasxEntidades EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCarrerasxEntidades(CarrerasxEntidad carrerasxEntidad)
        {
            base.AddObject("CarrerasxEntidades", carrerasxEntidad);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ProfesoresxCarreraesxEntidades EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToProfesoresxCarreraesxEntidades(ProfesoresxCarreraxEntidad profesoresxCarreraxEntidad)
        {
            base.AddObject("ProfesoresxCarreraesxEntidades", profesoresxCarreraxEntidad);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Formularios EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToFormularios(Formulario formulario)
        {
            base.AddObject("Formularios", formulario);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Faqdeu", Name="Carrera")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Carrera : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Carrera object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="nombre">Initial value of the Nombre property.</param>
        /// <param name="fechaCreacion">Initial value of the FechaCreacion property.</param>
        /// <param name="fechaModificacion">Initial value of the FechaModificacion property.</param>
        /// <param name="estado">Initial value of the Estado property.</param>
        public static Carrera CreateCarrera(global::System.Int32 id, global::System.String nombre, global::System.DateTime fechaCreacion, global::System.DateTime fechaModificacion, global::System.String estado)
        {
            Carrera carrera = new Carrera();
            carrera.Id = id;
            carrera.Nombre = nombre;
            carrera.FechaCreacion = fechaCreacion;
            carrera.FechaModificacion = fechaModificacion;
            carrera.Estado = estado;
            return carrera;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Nombre
        {
            get
            {
                return _Nombre;
            }
            set
            {
                OnNombreChanging(value);
                ReportPropertyChanging("Nombre");
                _Nombre = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Nombre");
                OnNombreChanged();
            }
        }
        private global::System.String _Nombre;
        partial void OnNombreChanging(global::System.String value);
        partial void OnNombreChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime FechaCreacion
        {
            get
            {
                return _FechaCreacion;
            }
            set
            {
                OnFechaCreacionChanging(value);
                ReportPropertyChanging("FechaCreacion");
                _FechaCreacion = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FechaCreacion");
                OnFechaCreacionChanged();
            }
        }
        private global::System.DateTime _FechaCreacion;
        partial void OnFechaCreacionChanging(global::System.DateTime value);
        partial void OnFechaCreacionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime FechaModificacion
        {
            get
            {
                return _FechaModificacion;
            }
            set
            {
                OnFechaModificacionChanging(value);
                ReportPropertyChanging("FechaModificacion");
                _FechaModificacion = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FechaModificacion");
                OnFechaModificacionChanged();
            }
        }
        private global::System.DateTime _FechaModificacion;
        partial void OnFechaModificacionChanging(global::System.DateTime value);
        partial void OnFechaModificacionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Estado
        {
            get
            {
                return _Estado;
            }
            set
            {
                OnEstadoChanging(value);
                ReportPropertyChanging("Estado");
                _Estado = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Estado");
                OnEstadoChanged();
            }
        }
        private global::System.String _Estado;
        partial void OnEstadoChanging(global::System.String value);
        partial void OnEstadoChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Faqdeu", "CarreraCarrerasxEntidad", "CarrerasxEntidad")]
        public EntityCollection<CarrerasxEntidad> Entidades
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<CarrerasxEntidad>("Faqdeu.CarreraCarrerasxEntidad", "CarrerasxEntidad");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<CarrerasxEntidad>("Faqdeu.CarreraCarrerasxEntidad", "CarrerasxEntidad", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Faqdeu", Name="CarrerasxEntidad")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class CarrerasxEntidad : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new CarrerasxEntidad object.
        /// </summary>
        /// <param name="carreraId">Initial value of the CarreraId property.</param>
        /// <param name="entidadId">Initial value of the EntidadId property.</param>
        public static CarrerasxEntidad CreateCarrerasxEntidad(global::System.Int32 carreraId, global::System.Int32 entidadId)
        {
            CarrerasxEntidad carrerasxEntidad = new CarrerasxEntidad();
            carrerasxEntidad.CarreraId = carreraId;
            carrerasxEntidad.EntidadId = entidadId;
            return carrerasxEntidad;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CarreraId
        {
            get
            {
                return _CarreraId;
            }
            set
            {
                if (_CarreraId != value)
                {
                    OnCarreraIdChanging(value);
                    ReportPropertyChanging("CarreraId");
                    _CarreraId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("CarreraId");
                    OnCarreraIdChanged();
                }
            }
        }
        private global::System.Int32 _CarreraId;
        partial void OnCarreraIdChanging(global::System.Int32 value);
        partial void OnCarreraIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 EntidadId
        {
            get
            {
                return _EntidadId;
            }
            set
            {
                if (_EntidadId != value)
                {
                    OnEntidadIdChanging(value);
                    ReportPropertyChanging("EntidadId");
                    _EntidadId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("EntidadId");
                    OnEntidadIdChanged();
                }
            }
        }
        private global::System.Int32 _EntidadId;
        partial void OnEntidadIdChanging(global::System.Int32 value);
        partial void OnEntidadIdChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Faqdeu", "CarreraCarrerasxEntidad", "Carrera")]
        public Carrera Carrera
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Carrera>("Faqdeu.CarreraCarrerasxEntidad", "Carrera").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Carrera>("Faqdeu.CarreraCarrerasxEntidad", "Carrera").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Carrera> CarreraReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Carrera>("Faqdeu.CarreraCarrerasxEntidad", "Carrera");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Carrera>("Faqdeu.CarreraCarrerasxEntidad", "Carrera", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Faqdeu", "EntidadCarrerasxEntidad", "Entidad")]
        public Entidad Entidad
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Entidad>("Faqdeu.EntidadCarrerasxEntidad", "Entidad").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Entidad>("Faqdeu.EntidadCarrerasxEntidad", "Entidad").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Entidad> EntidadReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Entidad>("Faqdeu.EntidadCarrerasxEntidad", "Entidad");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Entidad>("Faqdeu.EntidadCarrerasxEntidad", "Entidad", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Faqdeu", "CarrerasxEntidadProfesoresxCarreraxEntidad", "ProfesoresxCarreraxEntidad")]
        public EntityCollection<ProfesoresxCarreraxEntidad> Profesores
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<ProfesoresxCarreraxEntidad>("Faqdeu.CarrerasxEntidadProfesoresxCarreraxEntidad", "ProfesoresxCarreraxEntidad");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<ProfesoresxCarreraxEntidad>("Faqdeu.CarrerasxEntidadProfesoresxCarreraxEntidad", "ProfesoresxCarreraxEntidad", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Faqdeu", Name="Entidad")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Entidad : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Entidad object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="nombre">Initial value of the Nombre property.</param>
        /// <param name="tipo">Initial value of the Tipo property.</param>
        /// <param name="fechaCreacion">Initial value of the FechaCreacion property.</param>
        /// <param name="fechaModificacion">Initial value of the FechaModificacion property.</param>
        /// <param name="estado">Initial value of the Estado property.</param>
        public static Entidad CreateEntidad(global::System.Int32 id, global::System.String nombre, global::System.String tipo, global::System.DateTime fechaCreacion, global::System.DateTime fechaModificacion, global::System.String estado)
        {
            Entidad entidad = new Entidad();
            entidad.Id = id;
            entidad.Nombre = nombre;
            entidad.Tipo = tipo;
            entidad.FechaCreacion = fechaCreacion;
            entidad.FechaModificacion = fechaModificacion;
            entidad.Estado = estado;
            return entidad;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Nombre
        {
            get
            {
                return _Nombre;
            }
            set
            {
                OnNombreChanging(value);
                ReportPropertyChanging("Nombre");
                _Nombre = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Nombre");
                OnNombreChanged();
            }
        }
        private global::System.String _Nombre;
        partial void OnNombreChanging(global::System.String value);
        partial void OnNombreChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Tipo
        {
            get
            {
                return _Tipo;
            }
            set
            {
                OnTipoChanging(value);
                ReportPropertyChanging("Tipo");
                _Tipo = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Tipo");
                OnTipoChanged();
            }
        }
        private global::System.String _Tipo;
        partial void OnTipoChanging(global::System.String value);
        partial void OnTipoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime FechaCreacion
        {
            get
            {
                return _FechaCreacion;
            }
            set
            {
                OnFechaCreacionChanging(value);
                ReportPropertyChanging("FechaCreacion");
                _FechaCreacion = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FechaCreacion");
                OnFechaCreacionChanged();
            }
        }
        private global::System.DateTime _FechaCreacion;
        partial void OnFechaCreacionChanging(global::System.DateTime value);
        partial void OnFechaCreacionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime FechaModificacion
        {
            get
            {
                return _FechaModificacion;
            }
            set
            {
                OnFechaModificacionChanging(value);
                ReportPropertyChanging("FechaModificacion");
                _FechaModificacion = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FechaModificacion");
                OnFechaModificacionChanged();
            }
        }
        private global::System.DateTime _FechaModificacion;
        partial void OnFechaModificacionChanging(global::System.DateTime value);
        partial void OnFechaModificacionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Estado
        {
            get
            {
                return _Estado;
            }
            set
            {
                OnEstadoChanging(value);
                ReportPropertyChanging("Estado");
                _Estado = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Estado");
                OnEstadoChanged();
            }
        }
        private global::System.String _Estado;
        partial void OnEstadoChanging(global::System.String value);
        partial void OnEstadoChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Faqdeu", "EntidadCarrerasxEntidad", "CarrerasxEntidad")]
        public EntityCollection<CarrerasxEntidad> Carreras
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<CarrerasxEntidad>("Faqdeu.EntidadCarrerasxEntidad", "CarrerasxEntidad");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<CarrerasxEntidad>("Faqdeu.EntidadCarrerasxEntidad", "CarrerasxEntidad", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Faqdeu", Name="Formulario")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Formulario : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Formulario object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="nombre">Initial value of the Nombre property.</param>
        /// <param name="versión">Initial value of the Versión property.</param>
        /// <param name="fechaCreacion">Initial value of the FechaCreacion property.</param>
        /// <param name="fechaModificacion">Initial value of the FechaModificacion property.</param>
        public static Formulario CreateFormulario(global::System.Int32 id, global::System.String nombre, global::System.String versión, global::System.String fechaCreacion, global::System.String fechaModificacion)
        {
            Formulario formulario = new Formulario();
            formulario.Id = id;
            formulario.Nombre = nombre;
            formulario.Versión = versión;
            formulario.FechaCreacion = fechaCreacion;
            formulario.FechaModificacion = fechaModificacion;
            return formulario;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Nombre
        {
            get
            {
                return _Nombre;
            }
            set
            {
                OnNombreChanging(value);
                ReportPropertyChanging("Nombre");
                _Nombre = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Nombre");
                OnNombreChanged();
            }
        }
        private global::System.String _Nombre;
        partial void OnNombreChanging(global::System.String value);
        partial void OnNombreChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Versión
        {
            get
            {
                return _Versión;
            }
            set
            {
                OnVersiónChanging(value);
                ReportPropertyChanging("Versión");
                _Versión = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Versión");
                OnVersiónChanged();
            }
        }
        private global::System.String _Versión;
        partial void OnVersiónChanging(global::System.String value);
        partial void OnVersiónChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String FechaCreacion
        {
            get
            {
                return _FechaCreacion;
            }
            set
            {
                OnFechaCreacionChanging(value);
                ReportPropertyChanging("FechaCreacion");
                _FechaCreacion = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("FechaCreacion");
                OnFechaCreacionChanged();
            }
        }
        private global::System.String _FechaCreacion;
        partial void OnFechaCreacionChanging(global::System.String value);
        partial void OnFechaCreacionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String FechaModificacion
        {
            get
            {
                return _FechaModificacion;
            }
            set
            {
                OnFechaModificacionChanging(value);
                ReportPropertyChanging("FechaModificacion");
                _FechaModificacion = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("FechaModificacion");
                OnFechaModificacionChanged();
            }
        }
        private global::System.String _FechaModificacion;
        partial void OnFechaModificacionChanging(global::System.String value);
        partial void OnFechaModificacionChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Faqdeu", Name="Perfil")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Perfil : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Perfil object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="nombre">Initial value of the Nombre property.</param>
        /// <param name="fechaCreacion">Initial value of the FechaCreacion property.</param>
        /// <param name="fechaModificacion">Initial value of the FechaModificacion property.</param>
        /// <param name="estado">Initial value of the Estado property.</param>
        public static Perfil CreatePerfil(global::System.Int32 id, global::System.String nombre, global::System.DateTime fechaCreacion, global::System.DateTime fechaModificacion, global::System.String estado)
        {
            Perfil perfil = new Perfil();
            perfil.Id = id;
            perfil.Nombre = nombre;
            perfil.FechaCreacion = fechaCreacion;
            perfil.FechaModificacion = fechaModificacion;
            perfil.Estado = estado;
            return perfil;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Nombre
        {
            get
            {
                return _Nombre;
            }
            set
            {
                OnNombreChanging(value);
                ReportPropertyChanging("Nombre");
                _Nombre = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Nombre");
                OnNombreChanged();
            }
        }
        private global::System.String _Nombre;
        partial void OnNombreChanging(global::System.String value);
        partial void OnNombreChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime FechaCreacion
        {
            get
            {
                return _FechaCreacion;
            }
            set
            {
                OnFechaCreacionChanging(value);
                ReportPropertyChanging("FechaCreacion");
                _FechaCreacion = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FechaCreacion");
                OnFechaCreacionChanged();
            }
        }
        private global::System.DateTime _FechaCreacion;
        partial void OnFechaCreacionChanging(global::System.DateTime value);
        partial void OnFechaCreacionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime FechaModificacion
        {
            get
            {
                return _FechaModificacion;
            }
            set
            {
                OnFechaModificacionChanging(value);
                ReportPropertyChanging("FechaModificacion");
                _FechaModificacion = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FechaModificacion");
                OnFechaModificacionChanged();
            }
        }
        private global::System.DateTime _FechaModificacion;
        partial void OnFechaModificacionChanging(global::System.DateTime value);
        partial void OnFechaModificacionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Estado
        {
            get
            {
                return _Estado;
            }
            set
            {
                OnEstadoChanging(value);
                ReportPropertyChanging("Estado");
                _Estado = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Estado");
                OnEstadoChanged();
            }
        }
        private global::System.String _Estado;
        partial void OnEstadoChanging(global::System.String value);
        partial void OnEstadoChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Faqdeu", "PerfilUsuario", "Usuario")]
        public EntityCollection<Usuario> Usuarios
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Usuario>("Faqdeu.PerfilUsuario", "Usuario");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Usuario>("Faqdeu.PerfilUsuario", "Usuario", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Faqdeu", Name="Profesor")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Profesor : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Profesor object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="nombre">Initial value of the Nombre property.</param>
        /// <param name="fechaCreacion">Initial value of the FechaCreacion property.</param>
        /// <param name="fechaModificacion">Initial value of the FechaModificacion property.</param>
        /// <param name="estado">Initial value of the Estado property.</param>
        public static Profesor CreateProfesor(global::System.Int32 id, global::System.String nombre, global::System.String fechaCreacion, global::System.String fechaModificacion, global::System.String estado)
        {
            Profesor profesor = new Profesor();
            profesor.Id = id;
            profesor.Nombre = nombre;
            profesor.FechaCreacion = fechaCreacion;
            profesor.FechaModificacion = fechaModificacion;
            profesor.Estado = estado;
            return profesor;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Nombre
        {
            get
            {
                return _Nombre;
            }
            set
            {
                OnNombreChanging(value);
                ReportPropertyChanging("Nombre");
                _Nombre = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Nombre");
                OnNombreChanged();
            }
        }
        private global::System.String _Nombre;
        partial void OnNombreChanging(global::System.String value);
        partial void OnNombreChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String FechaCreacion
        {
            get
            {
                return _FechaCreacion;
            }
            set
            {
                OnFechaCreacionChanging(value);
                ReportPropertyChanging("FechaCreacion");
                _FechaCreacion = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("FechaCreacion");
                OnFechaCreacionChanged();
            }
        }
        private global::System.String _FechaCreacion;
        partial void OnFechaCreacionChanging(global::System.String value);
        partial void OnFechaCreacionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String FechaModificacion
        {
            get
            {
                return _FechaModificacion;
            }
            set
            {
                OnFechaModificacionChanging(value);
                ReportPropertyChanging("FechaModificacion");
                _FechaModificacion = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("FechaModificacion");
                OnFechaModificacionChanged();
            }
        }
        private global::System.String _FechaModificacion;
        partial void OnFechaModificacionChanging(global::System.String value);
        partial void OnFechaModificacionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Estado
        {
            get
            {
                return _Estado;
            }
            set
            {
                OnEstadoChanging(value);
                ReportPropertyChanging("Estado");
                _Estado = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Estado");
                OnEstadoChanged();
            }
        }
        private global::System.String _Estado;
        partial void OnEstadoChanging(global::System.String value);
        partial void OnEstadoChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Faqdeu", "ProfesorProfesoresxCarreraxEntidad", "ProfesoresxCarreraxEntidad")]
        public EntityCollection<ProfesoresxCarreraxEntidad> Carreras
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<ProfesoresxCarreraxEntidad>("Faqdeu.ProfesorProfesoresxCarreraxEntidad", "ProfesoresxCarreraxEntidad");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<ProfesoresxCarreraxEntidad>("Faqdeu.ProfesorProfesoresxCarreraxEntidad", "ProfesoresxCarreraxEntidad", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Faqdeu", Name="ProfesoresxCarreraxEntidad")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ProfesoresxCarreraxEntidad : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ProfesoresxCarreraxEntidad object.
        /// </summary>
        /// <param name="carrerasxEntidadCarreraId">Initial value of the CarrerasxEntidadCarreraId property.</param>
        /// <param name="carrerasxEntidadEntidadId">Initial value of the CarrerasxEntidadEntidadId property.</param>
        /// <param name="profesorId">Initial value of the ProfesorId property.</param>
        public static ProfesoresxCarreraxEntidad CreateProfesoresxCarreraxEntidad(global::System.Int32 carrerasxEntidadCarreraId, global::System.Int32 carrerasxEntidadEntidadId, global::System.Int32 profesorId)
        {
            ProfesoresxCarreraxEntidad profesoresxCarreraxEntidad = new ProfesoresxCarreraxEntidad();
            profesoresxCarreraxEntidad.CarrerasxEntidadCarreraId = carrerasxEntidadCarreraId;
            profesoresxCarreraxEntidad.CarrerasxEntidadEntidadId = carrerasxEntidadEntidadId;
            profesoresxCarreraxEntidad.ProfesorId = profesorId;
            return profesoresxCarreraxEntidad;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CarrerasxEntidadCarreraId
        {
            get
            {
                return _CarrerasxEntidadCarreraId;
            }
            set
            {
                if (_CarrerasxEntidadCarreraId != value)
                {
                    OnCarrerasxEntidadCarreraIdChanging(value);
                    ReportPropertyChanging("CarrerasxEntidadCarreraId");
                    _CarrerasxEntidadCarreraId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("CarrerasxEntidadCarreraId");
                    OnCarrerasxEntidadCarreraIdChanged();
                }
            }
        }
        private global::System.Int32 _CarrerasxEntidadCarreraId;
        partial void OnCarrerasxEntidadCarreraIdChanging(global::System.Int32 value);
        partial void OnCarrerasxEntidadCarreraIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CarrerasxEntidadEntidadId
        {
            get
            {
                return _CarrerasxEntidadEntidadId;
            }
            set
            {
                if (_CarrerasxEntidadEntidadId != value)
                {
                    OnCarrerasxEntidadEntidadIdChanging(value);
                    ReportPropertyChanging("CarrerasxEntidadEntidadId");
                    _CarrerasxEntidadEntidadId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("CarrerasxEntidadEntidadId");
                    OnCarrerasxEntidadEntidadIdChanged();
                }
            }
        }
        private global::System.Int32 _CarrerasxEntidadEntidadId;
        partial void OnCarrerasxEntidadEntidadIdChanging(global::System.Int32 value);
        partial void OnCarrerasxEntidadEntidadIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ProfesorId
        {
            get
            {
                return _ProfesorId;
            }
            set
            {
                if (_ProfesorId != value)
                {
                    OnProfesorIdChanging(value);
                    ReportPropertyChanging("ProfesorId");
                    _ProfesorId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ProfesorId");
                    OnProfesorIdChanged();
                }
            }
        }
        private global::System.Int32 _ProfesorId;
        partial void OnProfesorIdChanging(global::System.Int32 value);
        partial void OnProfesorIdChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Faqdeu", "CarrerasxEntidadProfesoresxCarreraxEntidad", "CarrerasxEntidad")]
        public CarrerasxEntidad CarreraxEntidad
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CarrerasxEntidad>("Faqdeu.CarrerasxEntidadProfesoresxCarreraxEntidad", "CarrerasxEntidad").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CarrerasxEntidad>("Faqdeu.CarrerasxEntidadProfesoresxCarreraxEntidad", "CarrerasxEntidad").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<CarrerasxEntidad> CarreraxEntidadReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CarrerasxEntidad>("Faqdeu.CarrerasxEntidadProfesoresxCarreraxEntidad", "CarrerasxEntidad");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<CarrerasxEntidad>("Faqdeu.CarrerasxEntidadProfesoresxCarreraxEntidad", "CarrerasxEntidad", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Faqdeu", "ProfesorProfesoresxCarreraxEntidad", "Profesor")]
        public Profesor Profesores
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Profesor>("Faqdeu.ProfesorProfesoresxCarreraxEntidad", "Profesor").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Profesor>("Faqdeu.ProfesorProfesoresxCarreraxEntidad", "Profesor").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Profesor> ProfesoresReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Profesor>("Faqdeu.ProfesorProfesoresxCarreraxEntidad", "Profesor");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Profesor>("Faqdeu.ProfesorProfesoresxCarreraxEntidad", "Profesor", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Faqdeu", Name="Usuario")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Usuario : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Usuario object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="nombre">Initial value of the Nombre property.</param>
        /// <param name="apellidoPaterno">Initial value of the ApellidoPaterno property.</param>
        /// <param name="apellidoMaterno">Initial value of the ApellidoMaterno property.</param>
        /// <param name="email">Initial value of the Email property.</param>
        /// <param name="clave">Initial value of the Clave property.</param>
        /// <param name="fechaCreacion">Initial value of the FechaCreacion property.</param>
        /// <param name="fechaModificacion">Initial value of the FechaModificacion property.</param>
        /// <param name="fechaNacimiento">Initial value of the FechaNacimiento property.</param>
        /// <param name="estado">Initial value of the Estado property.</param>
        public static Usuario CreateUsuario(global::System.Int32 id, global::System.String nombre, global::System.String apellidoPaterno, global::System.String apellidoMaterno, global::System.String email, global::System.String clave, global::System.DateTime fechaCreacion, global::System.DateTime fechaModificacion, global::System.DateTime fechaNacimiento, global::System.String estado)
        {
            Usuario usuario = new Usuario();
            usuario.Id = id;
            usuario.Nombre = nombre;
            usuario.ApellidoPaterno = apellidoPaterno;
            usuario.ApellidoMaterno = apellidoMaterno;
            usuario.Email = email;
            usuario.Clave = clave;
            usuario.FechaCreacion = fechaCreacion;
            usuario.FechaModificacion = fechaModificacion;
            usuario.FechaNacimiento = fechaNacimiento;
            usuario.Estado = estado;
            return usuario;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Nombre
        {
            get
            {
                return _Nombre;
            }
            set
            {
                OnNombreChanging(value);
                ReportPropertyChanging("Nombre");
                _Nombre = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Nombre");
                OnNombreChanged();
            }
        }
        private global::System.String _Nombre;
        partial void OnNombreChanging(global::System.String value);
        partial void OnNombreChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ApellidoPaterno
        {
            get
            {
                return _ApellidoPaterno;
            }
            set
            {
                OnApellidoPaternoChanging(value);
                ReportPropertyChanging("ApellidoPaterno");
                _ApellidoPaterno = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ApellidoPaterno");
                OnApellidoPaternoChanged();
            }
        }
        private global::System.String _ApellidoPaterno;
        partial void OnApellidoPaternoChanging(global::System.String value);
        partial void OnApellidoPaternoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ApellidoMaterno
        {
            get
            {
                return _ApellidoMaterno;
            }
            set
            {
                OnApellidoMaternoChanging(value);
                ReportPropertyChanging("ApellidoMaterno");
                _ApellidoMaterno = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ApellidoMaterno");
                OnApellidoMaternoChanged();
            }
        }
        private global::System.String _ApellidoMaterno;
        partial void OnApellidoMaternoChanging(global::System.String value);
        partial void OnApellidoMaternoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Email
        {
            get
            {
                return _Email;
            }
            set
            {
                OnEmailChanging(value);
                ReportPropertyChanging("Email");
                _Email = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Email");
                OnEmailChanged();
            }
        }
        private global::System.String _Email;
        partial void OnEmailChanging(global::System.String value);
        partial void OnEmailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Clave
        {
            get
            {
                return _Clave;
            }
            set
            {
                OnClaveChanging(value);
                ReportPropertyChanging("Clave");
                _Clave = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Clave");
                OnClaveChanged();
            }
        }
        private global::System.String _Clave;
        partial void OnClaveChanging(global::System.String value);
        partial void OnClaveChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime FechaCreacion
        {
            get
            {
                return _FechaCreacion;
            }
            set
            {
                OnFechaCreacionChanging(value);
                ReportPropertyChanging("FechaCreacion");
                _FechaCreacion = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FechaCreacion");
                OnFechaCreacionChanged();
            }
        }
        private global::System.DateTime _FechaCreacion;
        partial void OnFechaCreacionChanging(global::System.DateTime value);
        partial void OnFechaCreacionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime FechaModificacion
        {
            get
            {
                return _FechaModificacion;
            }
            set
            {
                OnFechaModificacionChanging(value);
                ReportPropertyChanging("FechaModificacion");
                _FechaModificacion = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FechaModificacion");
                OnFechaModificacionChanged();
            }
        }
        private global::System.DateTime _FechaModificacion;
        partial void OnFechaModificacionChanging(global::System.DateTime value);
        partial void OnFechaModificacionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> FechaUltimoAcceso
        {
            get
            {
                return _FechaUltimoAcceso;
            }
            set
            {
                OnFechaUltimoAccesoChanging(value);
                ReportPropertyChanging("FechaUltimoAcceso");
                _FechaUltimoAcceso = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FechaUltimoAcceso");
                OnFechaUltimoAccesoChanged();
            }
        }
        private Nullable<global::System.DateTime> _FechaUltimoAcceso;
        partial void OnFechaUltimoAccesoChanging(Nullable<global::System.DateTime> value);
        partial void OnFechaUltimoAccesoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime FechaNacimiento
        {
            get
            {
                return _FechaNacimiento;
            }
            set
            {
                OnFechaNacimientoChanging(value);
                ReportPropertyChanging("FechaNacimiento");
                _FechaNacimiento = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FechaNacimiento");
                OnFechaNacimientoChanged();
            }
        }
        private global::System.DateTime _FechaNacimiento;
        partial void OnFechaNacimientoChanging(global::System.DateTime value);
        partial void OnFechaNacimientoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Estado
        {
            get
            {
                return _Estado;
            }
            set
            {
                OnEstadoChanging(value);
                ReportPropertyChanging("Estado");
                _Estado = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Estado");
                OnEstadoChanged();
            }
        }
        private global::System.String _Estado;
        partial void OnEstadoChanging(global::System.String value);
        partial void OnEstadoChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Faqdeu", "PerfilUsuario", "Perfil")]
        public EntityCollection<Perfil> Perfiles
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Perfil>("Faqdeu.PerfilUsuario", "Perfil");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Perfil>("Faqdeu.PerfilUsuario", "Perfil", value);
                }
            }
        }

        #endregion

    }

    #endregion

    
}
